#!/usr/bin/env sh

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on            \
    top_padding                  6             \
    bottom_padding               6             \
    left_padding                 6             \
    right_padding                6             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add app="GIMP" manage=off
yabai -m rule --add app="Inkscape" manage=off
yabai -m rule --add app="Word" title="Find and Replace" manage=off
yabai -m rule --add app="Microsoft Remote Desktop" manage=off
yabai -m rule --add app="Python" manage=off
yabai -m rule --add app="Blender" manage=off
yabai -m rule --add app="Ultimaker Cura" manage=off

if [[ $USER == 'workstation' ]]; then
    echo "Using work profile."
    yabai -m signal --add \
	event=application_activated \
	app="^Microsoft Teams$" \
	action='${HOME}/.config/yabai/scripts/defeat-teams'

    yabai -m signal --add \
	event=window_focused \
	app="^Microsoft Teams$" \
	title="^Microsoft Teams Notification$" \
	action='${HOME}/.config/yabai/scripts/defeat-teams'
fi

echo "yabai configuration loaded.."
# Janky Borders
borders \
    active_color=0xffe1e3e4 \
    inactive_color=0xff494d64 \
    hidpi=on \
    width=6.0  &
